# This is a basic workflow to help you get started with Actions

name: DeployToBuild

defaults:
  run:
    working-directory: ./

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Acción inicializada
      
    - name: Run a one-line script
      run: npm install

    # Runs a set of commands using the runners shell
    - name: Build page
      run: npm run build
    - name: Commit report
      run: |
          git config --global user.name 'Raúl García Fernández'
          git config --global user.email 'raulgf92@users.noreply.github.com'
          git remote set-url --push origin https://your_username:$GITHUB_TOKEN@github.com/${{ github.repository }}
          git commit -am "Automated report"
          git push origin
